### ISSUE TITLE
AdcDetectorPlotter fcl broken.

### ISSUE THREAD

**Issue by dladams** [DUNE/dunedataprep#1]
Example 9 in the [duneproc tutorial 2](https://github.com/dladams/duneproc/blob/master/doc/tutorial02.md) was failing because it uses AdcDetectorPlotter fcl configs from protodune_dataprep_tools.fcl that were missing the SkipBadChannels field. I added those fields and verified the example now runs.

The change is committed to develop and I request if be included in the next dunesw release.

**Comment by calcuttj** [comment]
It will be in the next release
